### ISSUE TITLE
Create the Planet Animation

### ISSUE THREAD

**Issue by rishyendra333** [HackNC/fall2024#20]
Replace the raven + pumpkin graphic next to "what is HackNC" on the about portion of the website with the following planet animation https://drive.google.com/drive/folders/1PFyDkJZ-SDAijoDHMn5ahRjPVVeXW2CH.

Requirements:
The planets are rendered and their animation works.

**Comment by melanieohta** [comment]
Unsure if this was intentional by graphics team but background of animation isn't transparent. Also it doesn't have an exactly clean loop.

**Comment by rishyendra333** [comment]
> Unsure if this was intentional by graphics team but background of animation isn't transparent. Also it doesn't have an exactly clean loop.

I will get back to you on this

**Comment by rishyendra333** [comment]
> Unsure if this was intentional by graphics team but background of animation isn't transparent. Also it doesn't have an exactly clean loop.

So, apparently, the file type is only transparent for windows users, so graphics is working on making the background transparent. I'll update you when that is ready.

**Comment by aryasalian** [comment]
We fixed this up in another commit, so sorry to keep you hanging and thank you so much for your hard work!!
