### ISSUE TITLE
Remove 2023 Sponsors' Logos

### ISSUE THREAD

**Issue by aryasalian** [HackNC/fall2024#3]
- [x] Remove the **IMAGES/LINKS TO IMAGES** of the sponsor logos without deleting the code around it.
This helps us keep placeholders for the sponsor logos instead.

**Comment by aryasalian** [comment]
I should have mentioned this before but it would be nice if you could remove the links to the sponsor's websites too. Visually, the sponsor section should look empty.

**Comment by rishyendra333** [comment]
Arya fixed in his commit.
