### ISSUE TITLE
Add LinkedIn Link

### ISSUE THREAD

**Issue by aryasalian** [HackNC/fall2024#4]
- [x] Add a link to our LinkedIn at the end of the landing page

For this one, keep in mind all previous social media handles had logos accompanying it in the resources folder. Since we don't have the logo for LinkedIn in the resources folder yet, I don't mind if you manage to get a .svg form of the logo similar in style to the rest and add it to the resources folder which you later reference in your CSS for the LinkedIn logo.

If you do not manage to find it, please keep a tiny black box instead as a place holder and comment your code accordingly.

**Comment by vvkash** [comment]
Added the linkedin logo/link in the index.html file.

**Comment by vvkash** [comment]
Used the font-awesome library that was already imported to add the linkedin image and url.
