### ISSUE TITLE
Create a new webpage called "Meet the Team"

### ISSUE THREAD

**Issue by aryasalian** [HackNC/fall2024#6]
- [x] I personally would go about doing this by making a copy of the live folder and replacing the word live with "Meet the Team" everywhere on the website
- [x] We wouldn't need resources, tracks/prizes or schedule folder/tab on the website so please delete that from the live folder copy and you should be left with only an index.html file and a .DS_Store file which is just a binary file we don't need to bother about right now.
- [x] On the website, clear out all information that was earlier on the live page. Keep the link that takes us back to the landing page.
- [x] Replace the three lilac divs with attribute: [class="card full-width"] with two card full-width lilac divs where we will later put in images of directors and members respectively.

You would be left with a pretty empty website with no information but just a tab called "Meet the Team!", two lilac divs and all necessary formatting(the background for example) remains intact.

**Comment by vvkash** [comment]
Will get this done on Monday.

**Comment by aryasalian** [comment]
> Will get this done on Monday.

Sounds great!
