### ISSUE TITLE
Changing Footer and FAQ Text

### ISSUE THREAD

**Issue by rishyendra333** [HackNC/fall2024#78]
Change the footer to where the following is in one line:

© HackNC 2024 - MLH Code of Conduct - [icons for different social media links]

Add the following to the FAQ question about accommodation:

Overnight accommodation does not account for blankets, so be sure to bring your own.

**Comment by vvkash** [comment]
Updated branch

**Comment by vvkash** [comment]
updated branch with mobile view fix
